on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Call Deployment Workflow
        uses: organization/deployment-repo/.github/workflows/deploy.yml@main
      
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "text": "Deployment completed successfully!",
              "attachments": [
                {
                  "text": "Check the deployment logs for more details."
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Deployment completed successfully!"

      - name: Notify on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "text": "Deployment failed!",
              "attachments": [
                {
                  "text": "Check the deployment logs for more details."
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Deployment failed!"
