on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        version: [16, 18]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test

    - name: Display Node.js version
      run: |
        echo "Running tests with Node.js ${{ matrix.version }} on ${{matrix.os}}"
        node -v
        npm test
